#!/usr/bin/env python3

import json
import locale
import sys
import re
import reports_old
import io


def load_data(filename):
  """Loads the contents of filename as a JSON file."""
  json_file = io.open(filename,encoding='utf-8')
  data = json.load(json_file)
  json_file.close()
  print(data)
  return data


def format_car(car):
  """Given a car dictionary, return(s a nicely formatted name."""
  return "{} {} ({})".format(car["car_make"], car["car_model"], car["car_year"])


def process_data(data):
  """Analyzes the data, looking for maximums.

  Returns a list of lines that summarize the information.
  """
  max_revenue = {"revenue": 0}
  max_sales = {'total_sales':0}
  pattern = r".*\(([0-9]*)\)"
  dict_year_sales = {}
  for item in data:
    # Calculate the revenue generated by this model (price * total_sales)
    # We need to convert the price from "$1234.56" to 1234.56
    item_price = locale.atof(item["price"].strip("$"))
    item_revenue = item["total_sales"] * item_price
    if item_revenue > max_revenue["revenue"]:
      item["revenue"] = item_revenue
      max_revenue = item
    # keep track of max sales
    if item['total_sales'] > max_sales['total_sales']:
      max_sales = item
    # most popular year
    year = re.search(pattern, format_car(item['car'])).group(1)
    if year not in dict_year_sales.keys():
      dict_year_sales[year] = item["total_sales"]
    else:
      temp  = {}
      temp[year] = dict_year_sales.get(year) + item['total_sales']
      dict_year_sales.update(temp)
  sorted_dict_year_sales = sorted(dict_year_sales.items(), key=lambda item: item[1], reverse=True)
  most_sales_year, most_sales = sorted_dict_year_sales[0]
  summary = [
    "The {} generated the most revenue: ${:.2f}".format(format_car(max_revenue["car"]), max_revenue["revenue"]),
    "The {} had the most sales: {}".format(format_car(max_sales['car']),max_sales['total_sales']),
    "The most popular year was {} with {} sales.".format(most_sales_year, most_sales)
  ]

  return summary


def cars_dict_to_table(car_data):
  """Turns the data in car_data into a list of lists."""
  table_data = [["ID", "Car", "Price", "Total Sales"]]
  for item in car_data:
    table_data.append([item["id"], format_car(item["car"]), item["price"], item["total_sales"]])
  return table_data

def main(argv):
  """Process the JSON data and generate a full report out of it."""
  data = load_data("example.json")
  summary = process_data(data)
  ## pdf report"
  reports_old.generate("cars.pdf","Sales summary for last month","<br/>".join(summary),cars_dict_to_table(data))
  # TODO: send the PDF report as an email attachment

if __name__ == "__main__":
  main(sys.argv)